trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  branch: $(Build.SourceBranchName)

jobs:
- job: BuildAndSyncWithGitHub
  displayName: 'Build and Sync with GitHub'
  steps:
  - script: |
      git config --global user.name "$(Build.SourceVersionAuthor)"
      git config --global user.email "$(Build.SourceVersionAuthorEmail)"
      git remote add sync-repo https://github.com/KrisJCarroll/efficient-btw.git
      git fetch sync-repo
      git merge sync-repo/$(branch)
      git push sync-repo HEAD:$(branch)
    displayName: Sync changes with GitHub
#- task: Gradle@3
#  inputs:
#    gradleWrapperFile: 'gradlew'  # Path to your Gradle wrapper
#    tasks: 'build'  # Replace with the tasks you want to run
#    options: '-Xmx3072m' 
#    publishJUnitResults: true
#    testResultsFiles: '**/TEST-*.xml'  # Updated pattern for test result files
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.11'  # Replace with your JDK version
#    jdkArchitectureOption: 'x64'
